//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorSkin.Models
{
    using DoctorSkin.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Web.UI.WebControls;

    public partial class DoctorSkinEntities : DbContext
    {
        public DoctorSkinEntities()
            : base("name=myDatabase")
        {
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }

        public virtual DbSet<BlogDetails> BlogDetails { get; set; }
        public virtual DbSet<BlogTypes> BlogType { get; set; }

        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Medias> Medias { get; set; }

        public virtual DbSet<Services> Services { get; set; }

        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Feedbacks> Feedbacks { get; set; }

        public virtual DbSet<Brands> Brands { get; set; }

        public System.Data.Entity.DbSet<DoctorSkin.Models.ServicesDetails> ServicesDetails { get; set; }
    }
}
